apiVersion: v1
kind: Pod
metadata:
 name: amd-smi
spec:
 nodeSelector:
  feature.node.kubernetes.io/amd-gpu: "true"
 containers:
 - image: crmirror.lcpu.dev/docker.io/rocm/pytorch:latest
   name: amd-smi
   command: ["/bin/bash"]
   args: ["-c","amd-smi version && amd-smi monitor -ptum"]
   resources:
    limits:
      amd.com/gpu: 1
    requests:
      amd.com/gpu: 1
 restartPolicy: Never
