apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "x86"
spec:
  nodeLabels:
    hpc.lcpu.dev/partition: x86

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "gpu-a800"
spec:
  nodeLabels:
    nvidia.com/gpu-product: NVIDIA-A800-80GB-PCIe

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "gpu-l40"
spec:
  nodeLabels:
    nvidia.com/gpu-product: NVIDIA-L40-40GB-PCIe

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "x86-amd"
spec:
  nodeLabels:
    hpc.lcpu.dev/partition: x86_amd

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "arm"
spec:
  nodeLabels:
    hpc.lcpu.dev/partition: arm

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "npu"
spec:
  nodeLabels:
    hpc.lcpu.dev/partition: npu

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "npu-inf"
spec:
  nodeLabels:
    hpc.lcpu.dev/partition: npu-inf