apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostFilesystem
metadata:
  name: psp-host-filesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPaths:
      # - readOnly: true
      #   pathPrefix: "/foo"
      - pathPrefix: "/var/lib/lxcfs"
      - readOnly: true
        pathPrefix: "/usr/local/Ascend/driver"
      - readOnly: true
        pathPrefix: "/etc/ascend_install.info"
