apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: x86-amd-local-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/local-hostpath
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: hpc.lcpu.dev/partition
        values:
          - x86_amd

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: npu-local-data
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /data/openebs
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: hpc.lcpu.dev/partition
        values:
          - npu
