apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-time-slicing-config
  namespace: gpu-operator
data:
  v100-32gb-shared: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        # renameByDefault: true # Renames all GPU to nvidia.com/gpu.shared
        resources:
        - name: nvidia.com/gpu
          replicas: 16

  v100-16gb-shared: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 8

  # v100-16gb: |-
  #   version: v1
  #   flags:
  #     migStrategy: mixed
  #   sharing:
  #     timeSlicing:
  #       resources:
  #       - name: nvidia.com/gpu
  #         replicas: 8
  #       - name: nvidia.com/mig-1g.5gb
  #         replicas: 2
  #       - name: nvidia.com/mig-2g.10gb
  #         replicas: 2
  #       - name: nvidia.com/mig-3g.20gb
  #         replicas: 3
  #       - name: nvidia.com/mig-7g.40gb
  #         replicas: 7

  a100-80gb-shared: |-
    version: v1
    flags:
      migStrategy: single
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 6

  l40-shared: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 4

  a100-80gb: |-
    version: v1
    flags:
      migStrategy: single
