apiVersion: user-operator.lcpu.dev/v1alpha1
kind: UserCreationConfig
metadata:
  labels:
    app.kubernetes.io/name: user-operator
  name: namespace-prefix
spec:
  enabled: true
  namespacePrefix: u-
  resources:
    - |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ .Namespace }}
        labels:
          # pod-security.kubernetes.io/enforce: baseline
          ssh-operator.lcpu.dev/inject: conditional
          lxcfs.lcpu.dev/inject: enabled
          kueue.x-k8s.io/managed-namespace: "true"

---
apiVersion: user-operator.lcpu.dev/v1alpha1
kind: UserCreationConfig
metadata:
  labels:
    app.kubernetes.io/name: user-operator
  name: rbac-config
spec:
  enabled: true
  resources:
    - |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: rolebinding-user-{{ .Username }}
        namespace: {{ .Namespace }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: competitor-role
      subjects:
        - kind: User
          name: {{ .Username }}
        - kind: ServiceAccount
          name: default
          namespace: {{ .Namespace }}

---
apiVersion: user-operator.lcpu.dev/v1alpha1
kind: UserCreationConfig
metadata:
  labels:
    app.kubernetes.io/name: user-operator
  name: ssh-keypair
spec:
  enabled: true
  resources:
    - |
      apiVersion: ssh-operator.lcpu.dev/v1alpha1
      kind: SSHKeyPair
      metadata:
        name: default-ed25519
      spec: {}

---
apiVersion: user-operator.lcpu.dev/v1alpha1
kind: UserCreationConfig
metadata:
  labels:
    app.kubernetes.io/name: user-operator
  name: network-policy
spec:
  enabled: true
  resources:
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: default-deny-all
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
        ingress: []
        egress: []
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress-dns
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - ports:
              - port: 53
                protocol: UDP
              - port: 53
                protocol: TCP
            to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
    - |
      apiVersion: "cilium.io/v2"
      kind: CiliumNetworkPolicy
      metadata:
        name: "allow-to-kube-apiserver"
      spec:
        endpointSelector: {}
        egress:
          - toEntities:
            - kube-apiserver
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-painter-service
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - ports:
              - port: 23333
                protocol: TCP
            to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    app-name: painter
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-same-namespace
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
        ingress:
          - from:
            - podSelector: {}
        egress:
          - to:
            - podSelector: {}
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress-mirror-site
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - ports:
              - port: 80
                protocol: TCP
              - port: 443
                protocol: TCP
            to:
              - ipBlock:
                  cidr: 162.105.120.100/32
              - ipBlock:
                  cidr: 115.27.161.81/32
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress-public-80-443
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - ports:
              - port: 80
                protocol: TCP
              - port: 443
                protocol: TCP
              - port: 443
                protocol: UDP # QUIC
            to:
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                    - 10.0.0.0/8
                    - 192.168.0.0/16
                    - 172.16.0.0/12
                    - 224.0.0.0/4
                    - 255.255.255.255/32
                    - 115.27.0.0/16
                    - 162.105.0.0/16
                    - 202.38.140.0/27
                    - 202.112.7.0/24
                    - 202.205.131.0/24
                    - 211.68.72.0/21
    - |
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-egress-github-22
      spec:
        podSelector: {}
        policyTypes:
          - Egress
        egress:
          - ports:
              - port: 22
                protocol: TCP
            to:
              - ipBlock:
                  cidr: 192.30.252.0/22
              - ipBlock:
                  cidr: 185.199.108.0/22
              - ipBlock:
                  cidr: 140.82.112.0/20
              - ipBlock:
                  cidr: 143.55.64.0/20
              - ipBlock:
                  cidr: 20.201.28.151/32
              - ipBlock:
                  cidr: 20.205.243.166/32
              - ipBlock:
                  cidr: 20.87.245.0/32
              - ipBlock:
                  cidr: 4.237.22.38/32
              - ipBlock:
                  cidr: 20.207.73.82/32
              - ipBlock:
                  cidr: 20.27.177.113/32
              - ipBlock:
                  cidr: 20.200.245.247/32
              - ipBlock:
                  cidr: 20.175.192.147/32
              - ipBlock:
                  cidr: 20.233.83.145/32
              - ipBlock:
                  cidr: 20.29.134.23/32
              - ipBlock:
                  cidr: 20.199.39.232/32
              - ipBlock:
                  cidr: 20.217.135.5/32
              - ipBlock:
                  cidr: 4.225.11.198/32
              - ipBlock:
                  cidr: 4.208.26.197/32
              - ipBlock:
                  cidr: 20.26.156.215/32
              - ipBlock:
                  cidr: 20.201.28.152/32
              - ipBlock:
                  cidr: 20.205.243.160/32
              - ipBlock:
                  cidr: 20.87.245.4/32
              - ipBlock:
                  cidr: 4.237.22.40/32
              - ipBlock:
                  cidr: 20.207.73.83/32
              - ipBlock:
                  cidr: 20.27.177.118/32
              - ipBlock:
                  cidr: 20.200.245.248/32
              - ipBlock:
                  cidr: 20.175.192.146/32
              - ipBlock:
                  cidr: 20.233.83.149/32
              - ipBlock:
                  cidr: 20.29.134.19/32
              - ipBlock:
                  cidr: 20.199.39.227/32
              - ipBlock:
                  cidr: 20.217.135.4/32
              - ipBlock:
                  cidr: 4.225.11.200/32
              - ipBlock:
                  cidr: 4.208.26.198/32
              - ipBlock:
                  cidr: 20.26.156.214/32

---
apiVersion: user-operator.lcpu.dev/v1alpha1
kind: UserCreationConfig
metadata:
  labels:
    app.kubernetes.io/name: user-operator
  name: resource-limit
spec:
  enabled: true
  resources:
    - |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: default-resource-quota
      spec:
        hard: {}
    - |
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: default-limit-range
      spec:
        limits:
          - default:
              cpu: 1
              memory: 1Gi
              nvidia.com/gpu: 0
              huawei.com/Ascend910: 0
              huawei.com/Ascend310P: 0
            defaultRequest:
              cpu: 150m
              memory: 128Mi
              nvidia.com/gpu: 0
              huawei.com/Ascend910: 0
              huawei.com/Ascend310P: 0
            max:
              cpu: 64
              memory: 256Gi
              nvidia.com/gpu: 4
              huawei.com/Ascend910: 8
              huawei.com/Ascend310P: 8
            min:
              cpu: 10m
              memory: 1Mi
              nvidia.com/gpu: 0
              huawei.com/Ascend910: 0
              huawei.com/Ascend310P: 0
            type: Container

---
apiVersion: user-operator.lcpu.dev/v1alpha1
kind: UserCreationConfig
metadata:
  labels:
    app.kubernetes.io/name: user-operator
  name: localqueue
spec:
  enabled: true
  resources:
    - |
      apiVersion: kueue.x-k8s.io/v1beta1
      kind: LocalQueue
      metadata:
        name: default
        namespace: {{ .Namespace }}
      spec:
        clusterQueue: default-queue # OK
