---
- name: Kubeadm reset on all nodes
  hosts: all_nodes
  become: yes
  tasks:
    - name: Reset kubeadm
      shell: kubeadm reset -f
      ignore_errors: yes
      register: reset_output
    - name: Debug output
      debug:
        var: reset_output
    - name: Clean up all
      shell: |
        systemctl stop kubelet
        crictl rm --all
        crictl rmi --all
        systemctl stop containerd
        sudo rm -rf /etc/kubernetes
        sudo rm -rf ~/.kube
        sudo rm -rf /etc/cni/net.d
        sudo ip link delete cilium_host
        sudo ip link delete cilium_net
        sudo ip link delete cilium_vxlan
        sudo dnf remove kubeadm kubectl kubelet
      ignore_errors: yes
