---
- name: Kubeadm reset on all nodes
  hosts: all_nodes
  become: yes
  tasks:
    - name: Reset kubeadm
      shell: kubeadm reset -f
      ignore_errors: yes
      register: reset_output
    - name: Debug output
      debug:
        var: reset_output
