apiVersion: batch/v1
kind: Job
metadata:
  name: "stress-test-job"
  labels:
    app: "stress-test"
spec:
  template:
    spec:
      containers:
        - name: alpine
          image: alpine
          command: ["sleep", "300"]
      restartPolicy: Never
  backoffLimit: 4
