apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-pod
spec:
  containers:
    - name: nfs-client-container
      image: crmirror.lcpu.dev/xtlsoft/hpc_base:ubuntu2404
      command: ["sleep", "inf"]
      volumeMounts:
        - name: nfs-volume
          mountPath: /root
      workingDir: /
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "1"
          memory: "1Gi"
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: pvc-nfs-dynamic
