apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  nodeSelector:
    hpc.lcpu.dev/partition: x86
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep-infinity
spec:
  nodeSelector:
    hpc.lcpu.dev/partition: x86
  containers:
    - name: ubuntu
      image: crmirror.lcpu.dev/xtlsoft/hpc_base:ubuntu2404
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
