apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  nodeSelector:
    hpc.lcpu.dev/partition: x86
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
