apiVersion: v1
kind: Pod
metadata:
  name: sleep-infinity
spec:
  nodeSelector:
    hpc.lcpu.dev/partition: x86
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "2Gi"
