# Default values for kueue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# nameOverride: ""
# fullnameOverride: ""
# Enable each function, like kustomize https://github.com/kubernetes-sigs/kueue/blob/main/config/default/kustomization.yaml
enablePrometheus: false
# Enable x509 automated certificate management using cert-manager (cert-manager.io)
enableCertManager: false # IT HAS BUGS!!??
# Enable API Priority and Fairness configuration for the visibility API
enableVisibilityAPF: false
# Customize controllerManager
controllerManager:
  featureGates:
    - name: LocalQueueDefaulting
      enabled: true
  #  - name: PartialAdmission
  #    enabled: true
  manager:
    image:
      repository: crmirror.lcpu.dev/us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue
      # This should be set to 'IfNotPresent' for released version
      pullPolicy: IfNotPresent
    # podAnnotations: {}
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  replicas: 1
  # imagePullSecrets: []
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  topologySpreadConstraints: []
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
kubernetesClusterDomain: hpc.lcpu.dev
# controller_manager_config.yaml. controllerManager utilizes this yaml via manager-config Configmap.
managerConfig:
  controllerManagerConfigYaml: |-
    apiVersion: config.kueue.x-k8s.io/v1beta1
    kind: Configuration
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8643 # 8443 conflicts with kube-auth-proxy
    # enableClusterQueueResources: true
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: c1f6bfd2.kueue.x-k8s.io
    controller:
      groupKindConcurrency:
        Job.batch: 5
        Pod: 5
        Workload.kueue.x-k8s.io: 5
        LocalQueue.kueue.x-k8s.io: 1
        ClusterQueue.kueue.x-k8s.io: 1
        ResourceFlavor.kueue.x-k8s.io: 1
    clientConnection:
      qps: 150
      burst: 300
    #pprofBindAddress: :8083
    #waitForPodsReady:
    #  enable: false
    #  timeout: 5m
    #  blockAdmission: false
    #  requeuingStrategy:
    #    timestamp: Eviction
    #    backoffLimitCount: null # null indicates infinite requeuing
    #    backoffBaseSeconds: 60
    #    backoffMaxSeconds: 3600
    manageJobsWithoutQueueName: true
    managedJobsNamespaceSelector:
      matchLabels:
        kueue.x-k8s.io/managed-namespace: "true"
    #internalCertManagement:
    #  enable: false
    #  webhookServiceName: ""
    #  webhookSecretName: ""
    integrations:
      frameworks:
      - "batch/job"
      - "kubeflow.org/mpijob"
      - "ray.io/rayjob"
      - "ray.io/raycluster"
      - "jobset.x-k8s.io/jobset"
      - "kubeflow.org/mxjob"
      - "kubeflow.org/paddlejob"
      - "kubeflow.org/pytorchjob"
      - "kubeflow.org/tfjob"
      - "kubeflow.org/xgboostjob"
      - "pod"
      # - "deployment"
    #  externalFrameworks:
    #  - "Foo.v1.example.com"
    #  podOptions:
    #    namespaceSelector:
    #      matchExpressions:
    #        - key: kubernetes.io/metadata.name
    #          operator: NotIn
    #          values: [ kube-system, kueue-system ]
    #fairSharing:
    #  enable: true
    #  preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]
    resources:
      excludeResourcePrefixes:
        - rdma.hpc.lcpu.dev
      transformations:
        - input: nvidia.com/gpu
          strategy: Retain
          outputs:
            hpc.lcpu.dev/gpu-count: "1"
