- name: Bootstrap Kubernetes control-plane using kubeadm
  hosts: control
  become: yes
  tasks:
    - name: Copy kubeadm init configuration file to master node
      copy:
        src: ./kubeadm/init-config.yaml
        dest: /root/init-config.yaml
        mode: "0644"
      when: inventory_hostname == "xcat"

    - name: Initialize Kubernetes master node using the configuration file
      command: kubeadm init --config=/root/init-config.yaml --control-plane-endpoint "192.168.206.5:6443" --upload-certs
      when: inventory_hostname == "xcat"
      register: kubeadm_init

    - name: Save kubeadm join command
      copy:
        content: "{{ kubeadm_init.stdout_lines[-2] }}"
        dest: /tmp/kubeadm_join.sh
        mode: "0755"
      when: inventory_hostname == "xcat"

    - name: Copy kubeadm join command to worker nodes
      copy:
        src: /tmp/kubeadm_join.sh
        dest: /tmp/kubeadm_join.sh
        mode: "0755"
      when: inventory_hostname != "xcat"
