- name: Bootstrap Kubernetes control-plane using kubeadm
  hosts: ["xcat", "all_noctrl"]
  become: yes
  tasks:
    - name: Ensure kubeadm patches
      file:
        path: /root/kubeadm-patches
        state: directory
        mode: "0755"
      when: inventory_hostname != "xcat"

    - name: Insert kubeletconfiguration patch
      template:
        src: ./kubeadm/kubeletconfiguration0+strategic.yaml.j2
        dest: /root/kubeadm-patches/kubeletconfiguration0+strategic.yaml
        mode: "0644"
      when: inventory_hostname != "xcat"

    - name: Upgrade nodes to the cluster
      command: kubeadm upgrade node phase kubelet-config --patches=/root/kubeadm-patches/
      when: inventory_hostname != "xcat"
      register: kubeadm_join
      ignore_errors: yes

    - name: Clean up join config file
      file:
        path: /root/join-config.yaml
        state: absent
      when: inventory_hostname != "xcat"

    - name: Clean up kubeadm patches
      file:
        path: /root/kubeadm-patches
        state: absent
      when: inventory_hostname != "xcat"
