apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [{
             "resourcePrefix": "rdma.hpc.lcpu.dev",
             "resourceName": "hca_cx5_wm2",
             "rdmaHcaMax": 1000,
             "selectors": {
                 "vendors": ["15b3"]
             }
        }]
    }
