certmanager:
  enabled: false
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: hpc.lcpu.dev/partition
              operator: In
              values:
                - control
                - x86_amd
        weight: 1
