redisReplication:
  name: redis-replication
  clusterSize: 2
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      cpu: "8"
      memory: 16Gi

serviceMonitor:
  # enabled: true
  enabled: false # TODO: NEED TO DEPLOY PROMETHEUS OPERATOR FIRST

redisExporter:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

priorityClassName: system-cluster-critical

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: hpc.lcpu.dev/partition
              operator: In
              values:
                - x86
                # - x86_amd
        weight: 1

pdb:
  enabled: true
  minAvailable: 1

storageSpec:
  volumeClaimTemplate:
    spec:
      # storageClassName: x86-amd-local-hostpath
      storageClassName: openebs-hostpath
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 64Gi

externalConfig:
  enabled: true
  data: |
    tcp-keepalive 300
    appendonly yes
    appendfsync everysec
    maxmemory-policy noeviction

  # slowlog-max-len 128
  # stream-node-max-bytes 4096
