pdb:
  enabled: true
  minAvailable: 1

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: hpc.lcpu.dev/partition
              operator: In
              values:
                - x86_amd
        weight: 1

redisExporter:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

priorityClassName: system-cluster-critical

redisSentinel:
  clusterSize: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

redisSentinelConfig:
  redisReplicationName: "redis-replication"
