---
- name: Remove Rocky User & Setup Network
  hosts: ["x86", "gpu"]
  remote_user: cloud-user
  become: yes
  tasks:
    - name: Remove rocky user
      user:
        name: rocky
        state: absent
        remove: yes

    - name: Remove /home/rocky directory
      file:
        path: /home/rocky
        state: absent

    - name: Set default gateway using nmcli
      command: >
        nmcli connection modify "System eno2"
        ipv4.gateway 192.168.206.1

    - name: Restart network connection to apply changes
      command: >
        nmcli connection up "System eno2"

- name: User Management and SSH Key Setup - Copy SSH Key
  hosts: all_nodes
  tasks:
    - name: Ensure .ssh directory exists in root's home
      file:
        path: /root/.ssh
        state: directory
        mode: "0700"
        owner: root
        group: root

    - name: Copy authorized_keys to root's .ssh directory
      copy:
        src: ./authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: "0600"
        owner: root
        group: root
