---
- name: Configure Rocky Linux Repositories and Install Packages
  hosts: ["control", "x86", "x86_amd"]
  become: true

  tasks:
    - name: Comment out mirrorlist and set baseurl for rocky-extras.repo and rocky.repo
      lineinfile:
        path: "{{ item }}"
        regexp: "^mirrorlist="
        line: "#mirrorlist="
        backrefs: yes
      with_items:
        - /etc/yum.repos.d/rocky-extras.repo
        - /etc/yum.repos.d/rocky.repo
    - name: Set baseurl for rocky-extras.repo and rocky.repo
      replace:
        path: "{{ item }}"
        regexp: '^#baseurl=http://dl.rockylinux.org/\$contentdir'
        replace: "baseurl=https://mirrors.pku.edu.cn/rocky"
      with_items:
        - /etc/yum.repos.d/rocky-extras.repo
        - /etc/yum.repos.d/rocky.repo

    - name: Install dnf-command(config-manager)
      dnf:
        name: dnf-command(config-manager)
        state: present

    - name: Install epel-release
      dnf:
        name: epel-release
        state: present

    - name: Disable epel-cisco-openh264 repository
      command: dnf config-manager --set-disabled epel-cisco-openh264

    - name: Enable CRB repository
      command: dnf config-manager --set-enabled crb

    - name: Comment out metalink and set baseurl for epel.repo
      lineinfile:
        path: /etc/yum.repos.d/epel.repo
        regexp: "^metalink="
        line: "#metalink="
        backrefs: yes
    - name: Set baseurl for epel.repo from fedoraproject.org
      replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: "^#baseurl=https?://download.fedoraproject.org/pub/epel/"
        replace: "baseurl=https://mirrors.pku.edu.cn/epel/"
    - name: Set baseurl for epel.repo from example.com
      replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: "^#baseurl=https?://download.example/pub/epel/"
        replace: "baseurl=https://mirrors.pku.edu.cn/epel/"

    # - name: Update all packages
    #   dnf:
    #     name: "*"
    #     state: latest

    - name: Install common packages
      dnf:
        name:
          - vim
          - bash-completion
          - tmux
          - htop
          - nano
        state: present

    # - name: Install group packages
    #   dnf:
    #     name:
    #       - "@Headless Management"
    #       - "@System Tools"
    #       - "@Scientific Support"
    #       - "@Development Tools"
    #     state: present

    - name: Disable SELinux
      command: setenforce 0 && grubby --update-kernel ALL --args selinux=0

    # - name: Disable firewall
    #   command: systemctl disable --now firewalld

    # - name: Reboot the system
    #   reboot:
    #     msg: "Reboot initiated by Ansible for SELinux change"
    #     reboot_timeout: 600

- name: Configure OpenEuler Linux Repositories and Install Packages
  hosts: ["arm", "npu"]
  tasks:
    - name: Comment out metalink and set baseurl for openEuler.repo
      lineinfile:
        path: /etc/yum.repos.d/openEuler.repo
        regexp: "^metalink="
        line: "#metalink="
        backrefs: yes

    - name: Set baseurl for openEuler.repo
      replace:
        path: /etc/yum.repos.d/openEuler.repo
        regexp: "^#baseurl=http://repo.openeuler.org/"
        replace: "baseurl=https://mirrors.pku.edu.cn/openeuler/"

    - name: Install dnf-command(config-manager)
      dnf:
        name: dnf-command(config-manager)
        state: present

    - name: Install epel-release
      dnf:
        name: epel-release
        state: present

    - name: Disable epel-cisco-openh264 repository
      command: dnf config-manager --set-disabled epel-cisco-openh264

    - name: Enable CRB repository
      command: dnf config-manager --set-enabled crb

    # - name: Update all packages
    #   dnf:
    #     name: "*"
    #     state: latest

    - name: Install common packages
      dnf:
        name:
          - vim
          - bash-completion
          - tmux
          - htop
          - nano
        state: present

    # - name: Install group packages
    #   dnf:
    #     name:
    #       - "@Headless Management"
    #       - "@System Tools"
    #       - "@Scientific Support"
    #       - "@Development Tools"
    #     state: present

    - name: Disable SELinux
      command: setenforce 0 && grubby --update-kernel ALL --args selinux=0

    # - name: Disable firewall
    #   command: systemctl disable --now firewalld

    # - name: Reboot the system
    #   reboot:
    #     msg: "Reboot initiated by Ansible for SELinux change"
    #     reboot_timeout: 600
