- name: Mount NFS /cluster from 192.168.206.2
  hosts: x86
  become: yes
  tasks:
    - name: Install nfs-utils package
      ansible.builtin.package:
        name: nfs-utils
        state: present

    - name: Create mount point directory
      ansible.builtin.file:
        path: /cluster
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure NFS share is not added to /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "192.168.206.2:/cluster /cluster nfs defaults 0 0"
        state: absent

    - name: Mount NFS share
      ansible.builtin.mount:
        path: /cluster
        src: 192.168.206.2:/cluster
        fstype: nfs
        state: mounted
        opts: defaults
