- name: Install MLNX_OFED_LINUX
  hosts: ["x86", "gpu"]
  become: yes
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - perl
          - perl-sigtrap
          - tk
          - createrepo
          - kernel-rpm-macros
          - kernel-devel
          - pciutils
          - lsof
        state: present
    
    - name:  dnf groupinstall "Development Tools"
      ansible.builtin.command:
        cmd: dnf -y groupinstall "Development Tools"

    - name: Remove DOCA-Host
      shell: |
        dnf -y remove doca-host doca-ofed kmod-mlnx-nfsrdma

    - name: Install MLNX_OFED_LINUX with specified options
      ansible.builtin.command:
        cmd: ./mlnxofedinstall --all --with-nfsrdma --without-ucx --without-openmpi --force
        chdir: /cluster/MLNX_OFED_LINUX-24.10-1.1.4.0-rhel9.5-ext

    - name: unload xprtrdma kernel module
      shell: |
        modprobe -r xprtrdma
    
    - name: Reload the kernel modules
      ansible.builtin.command:
        cmd: /etc/init.d/openibd restart