---
- name: Copy etc-hosts file to all nodes
  hosts: all_nodes
  become: true

  tasks:
    - name: Copy the ./etc-hosts file to /etc/hosts on all nodes
      copy:
        src: ./etc-hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
