- name: Disable swap
  hosts: all_nodes
  become: true

  tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: "^[^#].*swap.*"
