- name: Disable swap
  hosts: all_noctrl
  become: true

  tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: "^[^#].*swap.*"

- name: Ensure IP forwarding is enabled and persisted
  hosts: all_nodes
  become: yes
  tasks:
    - name: Ensure /etc/sysctl.conf contains net.ipv4.ip_forward = 1
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net\.ipv4\.ip_forward='
        line: "net.ipv4.ip_forward=1"
        state: present

    - name: Apply sysctl settings to enable IP forwarding immediately
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

- name: Ensure SWAP is enabled and persisted on control nodes
  tasks:
    - name: Check if SWAP is already enabled
      command: swapon --show
      register: swap_status
      ignore_errors: yes

    - name: Enable SWAP if not already enabled
      command: swapon /dev/mapper/rl-swap
      when: swap_status.stdout_lines == ""

    - name: Ensure SWAP is persisted in /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "/dev/mapper/rl-swap none swap sw 0 0"
        create: yes
      when: swap_status.stdout_lines == ""

    - name: Verify SWAP is enabled
      command: swapon --show
      register: swap_verify
      changed_when: false

    - name: Debug SWAP status
      debug:
        var: swap_verify.stdout_lines
