- name: Disable swap
  hosts: all_nodes
  become: true

  tasks:
    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from /etc/fstab
      lineinfile:
        path: /etc/fstab
        state: absent
        regexp: "^[^#].*swap.*"

- name: Ensure IP forwarding is enabled and persisted
  hosts: all
  become: yes
  tasks:
    - name: Ensure /etc/sysctl.conf contains net.ipv4.ip_forward = 1
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net\.ipv4\.ip_forward='
        line: "net.ipv4.ip_forward=1"
        state: present

    - name: Apply sysctl settings to enable IP forwarding immediately
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes
